// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtklb784XyyOLxqHSJSbr3ly9Kiy47hPw',
    appId: '1:202241844743:web:445391070d931bdfe66ca2',
    messagingSenderId: '202241844743',
    projectId: 'fnailpro',
    authDomain: 'fnailpro.firebaseapp.com',
    storageBucket: 'fnailpro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCa1LaaSLOAni42eo2M26yoxLzviK8c5o',
    appId: '1:202241844743:android:cae4eea83e6a82fde66ca2',
    messagingSenderId: '202241844743',
    projectId: 'fnailpro',
    storageBucket: 'fnailpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzLZ-DeMm-dM9HiegL6h9JwAhhWCUcjXg',
    appId: '1:202241844743:ios:2aac23deef0d0bc7e66ca2',
    messagingSenderId: '202241844743',
    projectId: 'fnailpro',
    storageBucket: 'fnailpro.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );
}
